# Generated by Django 5.2.6 on 2025-10-10 01:55

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_phone'),
        ('listings', '0003_alter_listing_district_alter_listing_rooms_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-list_date',)},
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_title_6ba558_idx',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='screens',
        ),
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Private Rooms', 'Private Rooms'), ('Semi-Private Rooms', 'Semi-Private Rooms'), ('Standard (Multi-bed) Rooms', 'Standard (Multi-bed) Rooms')], default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='professionals',
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='services',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Services'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['list_date'], name='listings_li_list_da_153ce3_idx'),
        ),
        migrations.AddField(
            model_name='listing',
            name='professionals',
            field=models.ManyToManyField(blank=True, to='listings.subject'),
        ),
    ]
